export const phrases = [
  // Level 1: Very common patterns
  [
    { text: 'The sun rises in the', probable: 'morning', improbable: 'evening' },
    { text: 'The moon appears at', probable: 'night', improbable: 'noon' },
    { text: 'Birds fly in the', probable: 'sky', improbable: 'ground' },
    { text: 'Fish swim in the', probable: 'water', improbable: 'air' },
    { text: 'Flowers bloom in', probable: 'spring', improbable: 'winter' },
    { text: 'Leaves fall in', probable: 'autumn', improbable: 'summer' },
    { text: 'Snow falls in', probable: 'winter', improbable: 'summer' },
    { text: 'Rain falls from', probable: 'clouds', improbable: 'stars' },
    { text: 'Stars appear at', probable: 'night', improbable: 'dawn' },
    { text: 'The sun sets in the', probable: 'west', improbable: 'north' },
    { text: 'The wind blows from the', probable: 'north', improbable: 'ground' },
    { text: 'The ocean meets the', probable: 'shore', improbable: 'sky' },
    { text: 'Mountains touch the', probable: 'sky', improbable: 'ground' },
    { text: 'Rivers flow to the', probable: 'sea', improbable: 'sky' },
    { text: 'Clouds float in the', probable: 'sky', improbable: 'ground' },
    { text: 'Trees grow from the', probable: 'ground', improbable: 'sky' },
    { text: 'Birds nest in', probable: 'trees', improbable: 'ground' },
    { text: 'Fish live in the', probable: 'sea', improbable: 'sky' },
    { text: 'Bees make', probable: 'honey', improbable: 'water' },
    { text: 'Cows give', probable: 'milk', improbable: 'water' },
    { text: 'Chickens lay', probable: 'eggs', improbable: 'stones' },
    { text: 'Sheep give', probable: 'wool', improbable: 'leather' },
    { text: 'Birds have', probable: 'feathers', improbable: 'scales' },
    { text: 'Fish have', probable: 'scales', improbable: 'feathers' },
    { text: 'Trees have', probable: 'leaves', improbable: 'feathers' }
  ],
  // Level 2: Common actions and their typical objects
  [
    { text: 'People write with a', probable: 'pen', improbable: 'fork' },
    { text: 'People eat with a', probable: 'fork', improbable: 'pen' },
    { text: 'People drink from a', probable: 'cup', improbable: 'plate' },
    { text: 'People eat from a', probable: 'plate', improbable: 'cup' },
    { text: 'People sit on a', probable: 'chair', improbable: 'table' },
    { text: 'People eat at a', probable: 'table', improbable: 'chair' },
    { text: 'People sleep in a', probable: 'bed', improbable: 'chair' },
    { text: 'People drive a', probable: 'car', improbable: 'bike' },
    { text: 'People ride a', probable: 'bike', improbable: 'car' },
    { text: 'People wear', probable: 'clothes', improbable: 'food' },
    { text: 'People eat', probable: 'food', improbable: 'clothes' },
    { text: 'People read', probable: 'books', improbable: 'food' },
    { text: 'People watch', probable: 'TV', improbable: 'books' },
    { text: 'People listen to', probable: 'music', improbable: 'books' },
    { text: 'People play', probable: 'games', improbable: 'food' },
    { text: 'People cook', probable: 'food', improbable: 'games' },
    { text: 'People clean', probable: 'house', improbable: 'food' },
    { text: 'People wash', probable: 'clothes', improbable: 'food' },
    { text: 'People brush their', probable: 'teeth', improbable: 'hair' },
    { text: 'People comb their', probable: 'hair', improbable: 'teeth' },
    { text: 'People wear', probable: 'shoes', improbable: 'hats' },
    { text: 'People wear', probable: 'hats', improbable: 'shoes' },
    { text: 'People use', probable: 'phones', improbable: 'books' },
    { text: 'People read', probable: 'books', improbable: 'phones' },
    { text: 'People watch', probable: 'movies', improbable: 'books' }
  ],
  // Level 3: Common activities and their typical locations
  [
    { text: 'People swim in a', probable: 'pool', improbable: 'field' },
    { text: 'People play in a', probable: 'field', improbable: 'pool' },
    { text: 'People shop at a', probable: 'mall', improbable: 'pool' },
    { text: 'People eat at a', probable: 'restaurant', improbable: 'mall' },
    { text: 'People learn at a', probable: 'school', improbable: 'restaurant' },
    { text: 'People work at an', probable: 'office', improbable: 'school' },
    { text: 'People sleep at', probable: 'home', improbable: 'office' },
    { text: 'People exercise at a', probable: 'gym', improbable: 'home' },
    { text: 'People read at a', probable: 'library', improbable: 'gym' },
    { text: 'People watch at a', probable: 'theater', improbable: 'library' },
    { text: 'People swim at the', probable: 'beach', improbable: 'theater' },
    { text: 'People hike in the', probable: 'mountains', improbable: 'beach' },
    { text: 'People fish in the', probable: 'lake', improbable: 'mountains' },
    { text: 'People camp in the', probable: 'forest', improbable: 'lake' },
    { text: 'People ski on the', probable: 'slopes', improbable: 'forest' },
    { text: 'People surf on the', probable: 'waves', improbable: 'slopes' },
    { text: 'People walk in the', probable: 'park', improbable: 'waves' },
    { text: 'People run on the', probable: 'track', improbable: 'park' },
    { text: 'People play on the', probable: 'field', improbable: 'track' },
    { text: 'People dance in the', probable: 'club', improbable: 'field' },
    { text: 'People sing in the', probable: 'choir', improbable: 'club' },
    { text: 'People act in the', probable: 'theater', improbable: 'choir' },
    { text: 'People paint in the', probable: 'studio', improbable: 'theater' },
    { text: 'People cook in the', probable: 'kitchen', improbable: 'studio' },
    { text: 'People sleep in the', probable: 'bedroom', improbable: 'kitchen' }
  ],
  // Level 4: Common emotions and their typical causes
  [
    { text: 'People smile when they are', probable: 'happy', improbable: 'sad' },
    { text: 'People cry when they are', probable: 'sad', improbable: 'happy' },
    { text: 'People laugh when they are', probable: 'happy', improbable: 'angry' },
    { text: 'People frown when they are', probable: 'angry', improbable: 'happy' },
    { text: 'People jump when they are', probable: 'excited', improbable: 'tired' },
    { text: 'People yawn when they are', probable: 'tired', improbable: 'excited' },
    { text: 'People shake when they are', probable: 'scared', improbable: 'calm' },
    { text: 'People relax when they are', probable: 'calm', improbable: 'scared' },
    { text: 'People run when they are', probable: 'afraid', improbable: 'calm' },
    { text: 'People sleep when they are', probable: 'tired', improbable: 'afraid' },
    { text: 'People eat when they are', probable: 'hungry', improbable: 'tired' },
    { text: 'People drink when they are', probable: 'thirsty', improbable: 'hungry' },
    { text: 'People rest when they are', probable: 'tired', improbable: 'thirsty' },
    { text: 'People work when they are', probable: 'busy', improbable: 'tired' },
    { text: 'People play when they are', probable: 'free', improbable: 'busy' },
    { text: 'People study when they are', probable: 'focused', improbable: 'free' },
    { text: 'People talk when they are', probable: 'social', improbable: 'focused' },
    { text: 'People listen when they are', probable: 'interested', improbable: 'social' },
    { text: 'People watch when they are', probable: 'curious', improbable: 'interested' },
    { text: 'People read when they are', probable: 'quiet', improbable: 'curious' },
    { text: 'People write when they are', probable: 'inspired', improbable: 'quiet' },
    { text: 'People sing when they are', probable: 'joyful', improbable: 'inspired' },
    { text: 'People dance when they are', probable: 'happy', improbable: 'joyful' },
    { text: 'People paint when they are', probable: 'creative', improbable: 'happy' },
    { text: 'People cook when they are', probable: 'hungry', improbable: 'creative' }
  ],
  // Level 5: Common professions and their typical tools
  [
    { text: 'A chef uses a', probable: 'knife', improbable: 'hammer' },
    { text: 'A carpenter uses a', probable: 'hammer', improbable: 'knife' },
    { text: 'A writer uses a', probable: 'pen', improbable: 'hammer' },
    { text: 'A painter uses a', probable: 'brush', improbable: 'pen' },
    { text: 'A musician uses a', probable: 'instrument', improbable: 'brush' },
    { text: 'A doctor uses a', probable: 'stethoscope', improbable: 'instrument' },
    { text: 'A teacher uses a', probable: 'book', improbable: 'stethoscope' },
    { text: 'A driver uses a', probable: 'steering wheel', improbable: 'book' },
    { text: 'A pilot uses a', probable: 'controls', improbable: 'steering wheel' },
    { text: 'A sailor uses a', probable: 'compass', improbable: 'controls' },
    { text: 'A photographer uses a', probable: 'camera', improbable: 'compass' },
    { text: 'A gardener uses a', probable: 'shovel', improbable: 'camera' },
    { text: 'A barber uses a', probable: 'scissors', improbable: 'shovel' },
    { text: 'A tailor uses a', probable: 'needle', improbable: 'scissors' },
    { text: 'A mechanic uses a', probable: 'wrench', improbable: 'needle' },
    { text: 'A plumber uses a', probable: 'pipe', improbable: 'wrench' },
    { text: 'A electrician uses a', probable: 'wire', improbable: 'pipe' },
    { text: 'A builder uses a', probable: 'brick', improbable: 'wire' },
    { text: 'A farmer uses a', probable: 'tractor', improbable: 'brick' },
    { text: 'A fisherman uses a', probable: 'net', improbable: 'tractor' },
    { text: 'A hunter uses a', probable: 'gun', improbable: 'net' },
    { text: 'A soldier uses a', probable: 'weapon', improbable: 'gun' },
    { text: 'A police officer uses a', probable: 'badge', improbable: 'weapon' },
    { text: 'A firefighter uses a', probable: 'hose', improbable: 'badge' },
    { text: 'A nurse uses a', probable: 'thermometer', improbable: 'hose' }
  ],
  // Level 6: Common weather and its typical effects
  [
    { text: 'When it rains, people use', probable: 'umbrellas', improbable: 'sunglasses' },
    { text: 'When it snows, people wear', probable: 'coats', improbable: 'shorts' },
    { text: 'When it is hot, people wear', probable: 'shorts', improbable: 'coats' },
    { text: 'When it is cold, people wear', probable: 'sweaters', improbable: 'shorts' },
    { text: 'When it is windy, people wear', probable: 'jackets', improbable: 'sweaters' },
    { text: 'When it is sunny, people wear', probable: 'sunglasses', improbable: 'jackets' },
    { text: 'When it is foggy, people use', probable: 'lights', improbable: 'sunglasses' },
    { text: 'When it is stormy, people stay', probable: 'inside', improbable: 'outside' },
    { text: 'When it is clear, people go', probable: 'outside', improbable: 'inside' },
    { text: 'When it is cloudy, people bring', probable: 'jackets', improbable: 'shorts' },
    { text: 'When it is humid, people use', probable: 'fans', improbable: 'heaters' },
    { text: 'When it is dry, people use', probable: 'lotion', improbable: 'fans' },
    { text: 'When it is wet, people use', probable: 'towels', improbable: 'lotion' },
    { text: 'When it is icy, people walk', probable: 'slowly', improbable: 'quickly' },
    { text: 'When it is warm, people open', probable: 'windows', improbable: 'doors' },
    { text: 'When it is cool, people close', probable: 'windows', improbable: 'doors' },
    { text: 'When it is dark, people turn on', probable: 'lights', improbable: 'fans' },
    { text: 'When it is bright, people close', probable: 'curtains', improbable: 'lights' },
    { text: 'When it is quiet, people can', probable: 'hear', improbable: 'see' },
    { text: 'When it is loud, people cover their', probable: 'ears', improbable: 'eyes' },
    { text: 'When it is smelly, people cover their', probable: 'nose', improbable: 'ears' },
    { text: 'When it is dusty, people cover their', probable: 'mouth', improbable: 'nose' },
    { text: 'When it is smoky, people open', probable: 'windows', improbable: 'doors' },
    { text: 'When it is foggy, people drive', probable: 'slowly', improbable: 'quickly' },
    { text: 'When it is clear, people drive', probable: 'normally', improbable: 'slowly' }
  ],
  // Level 7: Common time periods and typical activities
  [
    { text: 'In the morning, people', probable: 'wake up', improbable: 'go to bed' },
    { text: 'At noon, people', probable: 'eat lunch', improbable: 'eat dinner' },
    { text: 'In the afternoon, people', probable: 'work', improbable: 'sleep' },
    { text: 'In the evening, people', probable: 'eat dinner', improbable: 'eat breakfast' },
    { text: 'At night, people', probable: 'sleep', improbable: 'work' },
    { text: 'On weekdays, people', probable: 'work', improbable: 'rest' },
    { text: 'On weekends, people', probable: 'rest', improbable: 'work' },
    { text: 'In summer, people', probable: 'swim', improbable: 'ski' },
    { text: 'In winter, people', probable: 'ski', improbable: 'swim' },
    { text: 'In spring, people', probable: 'plant', improbable: 'harvest' },
    { text: 'In autumn, people', probable: 'harvest', improbable: 'plant' },
    { text: 'On holidays, people', probable: 'celebrate', improbable: 'work' },
    { text: 'On birthdays, people', probable: 'party', improbable: 'work' },
    { text: 'On anniversaries, people', probable: 'celebrate', improbable: 'work' },
    { text: 'On vacations, people', probable: 'relax', improbable: 'work' },
    { text: 'On business trips, people', probable: 'work', improbable: 'relax' },
    { text: 'On school days, people', probable: 'study', improbable: 'play' },
    { text: 'On holidays, people', probable: 'play', improbable: 'study' },
    { text: 'On work days, people', probable: 'commute', improbable: 'relax' },
    { text: 'On rest days, people', probable: 'relax', improbable: 'commute' },
    { text: 'On special days, people', probable: 'celebrate', improbable: 'work' },
    { text: 'On regular days, people', probable: 'work', improbable: 'celebrate' },
    { text: 'On busy days, people', probable: 'rush', improbable: 'relax' },
    { text: 'On quiet days, people', probable: 'relax', improbable: 'rush' },
    { text: 'On important days, people', probable: 'prepare', improbable: 'relax' }
  ],
  // Level 8: Common locations and typical activities
  [
    { text: 'At home, people', probable: 'relax', improbable: 'work' },
    { text: 'At work, people', probable: 'work', improbable: 'relax' },
    { text: 'At school, people', probable: 'study', improbable: 'play' },
    { text: 'At the park, people', probable: 'play', improbable: 'study' },
    { text: 'At the beach, people', probable: 'swim', improbable: 'ski' },
    { text: 'At the pool, people', probable: 'swim', improbable: 'run' },
    { text: 'At the gym, people', probable: 'exercise', improbable: 'sleep' },
    { text: 'At the library, people', probable: 'read', improbable: 'play' },
    { text: 'At the theater, people', probable: 'watch', improbable: 'read' },
    { text: 'At the restaurant, people', probable: 'eat', improbable: 'sleep' },
    { text: 'At the cafe, people', probable: 'drink', improbable: 'eat' },
    { text: 'At the mall, people', probable: 'shop', improbable: 'sleep' },
    { text: 'At the hospital, people', probable: 'heal', improbable: 'play' },
    { text: 'At the airport, people', probable: 'travel', improbable: 'stay' },
    { text: 'At the station, people', probable: 'wait', improbable: 'play' },
    { text: 'At the office, people', probable: 'work', improbable: 'play' },
    { text: 'At the factory, people', probable: 'work', improbable: 'play' },
    { text: 'At the farm, people', probable: 'work', improbable: 'play' },
    { text: 'At the market, people', probable: 'shop', improbable: 'work' },
    { text: 'At the store, people', probable: 'buy', improbable: 'sell' },
    { text: 'At the bank, people', probable: 'save', improbable: 'spend' },
    { text: 'At the post office, people', probable: 'mail', improbable: 'buy' },
    { text: 'At the gas station, people', probable: 'fill', improbable: 'empty' },
    { text: 'At the pharmacy, people', probable: 'buy', improbable: 'sell' },
    { text: 'At the barber, people', probable: 'cut', improbable: 'grow' }
  ],
  // Level 9: Common objects and their typical uses
  [
    { text: 'A pen is used to', probable: 'write', improbable: 'eat' },
    { text: 'A fork is used to', probable: 'eat', improbable: 'write' },
    { text: 'A cup is used to', probable: 'drink', improbable: 'eat' },
    { text: 'A plate is used to', probable: 'eat', improbable: 'drink' },
    { text: 'A chair is used to', probable: 'sit', improbable: 'stand' },
    { text: 'A table is used to', probable: 'eat', improbable: 'sleep' },
    { text: 'A bed is used to', probable: 'sleep', improbable: 'eat' },
    { text: 'A door is used to', probable: 'enter', improbable: 'exit' },
    { text: 'A window is used to', probable: 'look', improbable: 'enter' },
    { text: 'A phone is used to', probable: 'call', improbable: 'eat' },
    { text: 'A TV is used to', probable: 'watch', improbable: 'listen' },
    { text: 'A radio is used to', probable: 'listen', improbable: 'watch' },
    { text: 'A fridge is used to', probable: 'cool', improbable: 'heat' },
    { text: 'An oven is used to', probable: 'heat', improbable: 'cool' },
    { text: 'A sink is used to', probable: 'wash', improbable: 'cook' },
    { text: 'A shower is used to', probable: 'wash', improbable: 'eat' },
    { text: 'A toothbrush is used to', probable: 'brush', improbable: 'eat' },
    { text: 'A towel is used to', probable: 'dry', improbable: 'wet' },
    { text: 'A lamp is used to', probable: 'light', improbable: 'dark' },
    { text: 'A key is used to', probable: 'open', improbable: 'close' },
    { text: 'A lock is used to', probable: 'close', improbable: 'open' },
    { text: 'A bag is used to', probable: 'carry', improbable: 'wear' },
    { text: 'A box is used to', probable: 'store', improbable: 'wear' },
    { text: 'A cup is used to', probable: 'hold', improbable: 'wear' },
    { text: 'A plate is used to', probable: 'serve', improbable: 'wear' }
  ],
  // Level 10: Common actions and their typical results
  [
    { text: 'When people work, they', probable: 'earn', improbable: 'spend' },
    { text: 'When people save, they', probable: 'keep', improbable: 'lose' },
    { text: 'When people spend, they', probable: 'buy', improbable: 'sell' },
    { text: 'When people study, they', probable: 'learn', improbable: 'forget' },
    { text: 'When people practice, they', probable: 'improve', improbable: 'worsen' },
    { text: 'When people exercise, they', probable: 'strengthen', improbable: 'weaken' },
    { text: 'When people rest, they', probable: 'recover', improbable: 'tire' },
    { text: 'When people sleep, they', probable: 'dream', improbable: 'work' },
    { text: 'When people eat, they', probable: 'nourish', improbable: 'starve' },
    { text: 'When people drink, they', probable: 'hydrate', improbable: 'dehydrate' },
    { text: 'When people cook, they', probable: 'prepare', improbable: 'consume' },
    { text: 'When people clean, they', probable: 'organize', improbable: 'mess' },
    { text: 'When people build, they', probable: 'create', improbable: 'destroy' },
    { text: 'When people fix, they', probable: 'repair', improbable: 'break' },
    { text: 'When people plant, they', probable: 'grow', improbable: 'kill' },
    { text: 'When people water, they', probable: 'nourish', improbable: 'dry' },
    { text: 'When people harvest, they', probable: 'collect', improbable: 'plant' },
    { text: 'When people fish, they', probable: 'catch', improbable: 'release' },
    { text: 'When people hunt, they', probable: 'find', improbable: 'lose' },
    { text: 'When people search, they', probable: 'find', improbable: 'lose' },
    { text: 'When people ask, they', probable: 'receive', improbable: 'give' },
    { text: 'When people give, they', probable: 'share', improbable: 'keep' },
    { text: 'When people take, they', probable: 'keep', improbable: 'share' },
    { text: 'When people share, they', probable: 'give', improbable: 'take' },
    { text: 'When people help, they', probable: 'support', improbable: 'hinder' }
  ]
]; 